#ifndef TYPEMODEL_H
#define TYPEMODEL_H

enum TypeModel {

    NONE_TYPE_MODEL = 0,
    DISCIPLINE_TYPE_MODEL,
    TASK_TYPE_MODEL,
    TEST_TYPE_MODEL,
    ABOUT_TEST_TYPE_MODEL,

    STATIC_ANALYZE_MODEL,
    ABOUT_STATIC_ANALYZE_MODEL,

    MENU_TYPE_MODEL,

    DISCIPLINE_DESCRIPTION_TYPE_MODEL,
    TASK_DESCRIPTION_TYPE_MODEL
};

#endif // TYPEMODEL_H
