#ifndef MODELITEMDESCRIPTORNOTIFICATION_H
#define MODELITEMDESCRIPTORNOTIFICATION_H

enum ModelItemDescriptorNotification {

    START_NOTIFICATION = 0,
    STOP_NOTIFICATION = 1
};

#endif // MODELITEMDESCRIPTORNOTIFICATION_H
