#ifndef MODELITEMDESCRIPTORTYPE_H
#define MODELITEMDESCRIPTORTYPE_H

enum ModelItemDescriptorType {

    BASED_MODEL_ITEM_DESCRIPTOR = 0,
    TREE_MODEL_ITEM_DESCRIPTOR,
    MODEL_BY_QACTION_ITEM_DESCRIPTOR
};

#endif
