#ifndef VIEW_CONTEXT_TYPE_H
#define VIEW_CONTEXT_TYPE_H

enum ViewContextType {

    DISCIPLINE_DESCRIPTION_VIEW_CONTEXT = 1,
    TASK_DESCRIPTION_VIEW_CONTEXT,

    DISCIPLINE_VIEW_CONTEXT,
    TEST_VIEW_CONTEXT,
    ABOUT_TEST_VIEW_CONTEXT,

    ANALYZE_VIEW_CONTEXT,
    ANALYZE_DESSCRIPTION_VIEW_CONTEXT,

    ATTACH_PROJECT_VIEW_CONTEXT,
    RUN_PROJECT_VIEW_CONTEXT,

    SIDE_MENU_VIEW_CONTEXT
};

#endif
